coffee/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resources :recipe
  resources :admin
  get '/outlines' => 'outlines#index'
  # root
  root 'outlines#index'
end

coffee/app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipes
end

coffee/app/models/order.rb
class Order < ApplicationRecord
    has_many :order_lists
    belongs_to :user
end

coffee/app/models/order_list.rb
class OrderList < ApplicationRecord
    belongs_to :product
    belongs_to :order
    belongs_to :user
end

coffee/app/models/product.rb
class Product < ApplicationRecord
    has_many :recipes
    has_many :order_lists
    belongs_to :user
end

coffee/app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :product
    belongs_to :ingredient
end

coffee/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :order_lists
end

coffee/app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end

  def create
    Ingredient.create(
      name: params[:name],
      category: params[:category],
      price: params[:price],
      comment: params[:comment],
    )
    redirect_to '/admin/new'
  end
end

coffee/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @products = Product.where(user_id: 1)
    end

    def create
        # order 생성
        order = Order.create(price: params[:val_hidden], user_id: 1)

        params[:checked_pct].split(",").each do |product_id| 
            # orderList 생성
            OrderList.create(user_id: 1, product_id: product_id, order_id: order.id)

            # product 변경
            product = Product.find_by(product_id)
            product.update(confirm: 'true')
        end
    end
end

coffee/app/controllers/recipe_controller.rb
class RecipeController < ApplicationController


  def index
    # 여기 아래는 지우셔도 됩니다.
    # @coffees=Ingredient.where(category: "coffee")
    # @waters=Ingredient.where(category: "water")
    # @milks=Ingredient.where(category: "milk")
    # @bubbles=Ingredient.where(category: "bubble")
    # @syrups=Ingredient.where(category: "syrup")
    # @decos=Ingredient.where(category: "deco")
    
    @ingredients = Ingredient.all
    @categories = Ingredient.select(:category).distinct.order(:category)
  end

  def create

    # {
    #   "pct_name"=>"테스트 이름입니다.",
    #   "pct_comment"=>"테스트 코멘트입니다.",
    #   "pct_price"=>"50800",
    #   "checked"=>"{\"3\":\"100\",\"4\":\"140\"}",
    # }

    # 값은 위와 같이 넘어옵니다.
    # checked = {ingredient_id => quantity}입니다.

    # JSON()을 거치면 checked가 아래와 같이 변하니 이 코드를 꼭 넣고 그 뒤에 hash로 코딩하시면 됩니다!!
    # "{\"3\":\"100\",\"4\":\"140\"}" => {"3"=>"100", "4"=>"140"}
    checked = JSON(params[:checked])
    
    # To Do List
    # 1. product를 만든다.
    # 2. recipe를 만든다.
    #   2-1. product_id는 방금 만든 product.id
    #   2-2. ingredient_id와 quantity는 checked를 사용하시면 됩니다.
    #   2-3. price = ingredient의 price * quantity입니다. 혹시 이부분 모르시면 물어보세요!



    # 아래 코드는 원래있던 product만드는 코드입니다. 주석처리 해놨습니다. 풀고 사용하시면 되요!

    # Product.create(
    #   name: params[:name],
    #   comment: params[:comment],
    #   price: "1000",
    #   user_id: 1,
    #   confirm: "false"
    # )

    redirect_to '/orders'
  end

end

coffee/app/helpers/admin_helper.rb
module AdminHelper
end

coffee/app/helpers/ajaxs_helper.rb
module AjaxsHelper
end

coffee/app/helpers/recipe_helper.rb
module RecipeHelper
end

coffee/app/views/admin/new.html.erb
<!--start wrapper-->
<section class="wrapper">
  <section class="page_head">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12">
                 <nav id="breadcrumbs">
                      <ul>
                          <li><a href="index.html">Home</a></li>
                          <li>Pages</li>
                      </ul>
                  </nav>

                  <div class="page_title">
                      <h2>재료를 추가하는 창입니다.</h2>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <section class="content typography">
    <div class="container">
      <div class="row sub_content">
        <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="dividerHeading">
            <h4><span>재료추가</span></h4>

          </div>
        </div>
        <div class="mrgb-50 clearfix"></div>
        <div class="pricingBlock theme-color-pt">
          <!--  DARK-BLUE PRICE ITEM  -->
          <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="pricingTable"><!-- BODY BOX-->
              <div class="pricingTable-header"><!-- HEADER BOX-->
                <span class="heading">재료 추가</span>
                <span class="price-value"><span>재료추가</span><span class="mo">!</span></span>
              </div><!--/ BODY BOX-->

              <div class="pricingContent">
                <%= form_tag(admin_index_path, method: "post") do %>
                <ul>
                  <li><strong>이름</strong> : <%=text_field_tag 'name' %></li>
                  <li><strong>카테고리</strong> :
                    <div class="radio">
    <label><input type="radio" name="category" value="coffee">커피</label>
    <label><input type="radio" name="category" value="water">물</label>
    <label><input type="radio" name="category" value="milk">우유</label>
    <label><input type="radio" name="category" value="bubble">거품</label>
    <label><input type="radio" name="category" value="syrup">시럽</label>
    <label><input type="radio" name="category" value="deco">데코</label>

  </div></li>
                  <li><strong>가격</strong> : <%=text_field_tag 'price' %></li>
                  <li><strong>설명</strong> : <%=text_field_tag 'comment' %></li>
                </ul>
              </div><!-- /  CONTENT BOX-->

              <div class="pricingTable-sign-up"><!-- BUTTON BOX-->
                <input type ="submit" class="btn btn-block btn-default" value="확인">
              </div><!-- BUTTON BOX-->

              <% end %>
            </div><!--/ BODY BOX-->
          </div>

        </div>
      </div>
    </div>
  </section>
      <section class="promo_box">
          <div class="container">
              <div class="row">
                  <div class="col-sm-9">
                      <div class="promo_content">
                          <h3>멋쟁이사자처럼 6기 운영진</h3>
                          <p>공부하기 위해서 만들었습니다.</p>
                      </div>
                  </div>
                  <div class="col-sm-3">
                      <div class="pb_action">
                          <a class="btn btn-lg btn-default" href="#fakelink">
                              <i class="fa fa-shopping-cart"></i>
                              서비스설명
                          </a>
                      </div>
                  </div>
              </div>
          </div>
      </section>
</section>	<!--end wrapper-->

coffee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%>

  </head>
  <body>
    <header id="header">
    <!-- Start header-top -->
    <div class="header-top">
        <div class="container">
        <br>
        </div>
    </div>
    <!--/.header-top -->

    <div id="menu-bar">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <div id="logo">
                        <h1><a href="/outlines"><%= image_tag "bootstrap/logo.png" %></a></h1>
                    </div>
                </div>
                <!-- Navigation
                ================================================== -->
                <div class="col-lg-9 col-sm-9 navbar navbar-default navbar-static-top container" role="navigation">
                    <!--  <div class="container">-->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav" id="nav-bar">
                            <li id="nav_home"><a href="/outlines"><span class="data-hover"data-hover="home">home</span></a>
                            </li>
                            <li id="nav_contact"><a href="/outlines"><span class="data-hover"data-hover="서비스">서비스</span></a>
                              <ul class="dropdown-menu">
                                  <li><a href="services.html">서비스</a></li>
                                  <li><a href="faq.html">FAQ</a></li>
                                  <li><a href="sidebar-right.html">연락처</a></li>
                              </ul>
                            </li>
                            <li id="nav_pct"><a href="#"><span class="data-hover" data-hover="음료">음료</span></a>
                                <ul class="dropdown-menu">
                                    <li><%= link_to '만들기',recipe_index_path()%></li>
                                    <li><%= link_to '주문하기', orders_path() %></li>
                                </ul>
                            </li>

                            <li><a href="#" ><span class="data-hover" data-hover="관리자">관리자</span></a>
                                <ul class="dropdown-menu">
                                    <li><%=link_to '재료만들기', new_admin_path()%></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!--/.container -->
    </div>
    <!--/#menu-bar -->
    </header>
    <!--End Header-->


    <%= yield %>

  </body>
</html>

coffee/app/views/orders/create.html.erb
<div style="display: flex;justify-content: center;">
    <div class="col-sm-6 col-lg-4">
        <div class="serviceBox_3"  style="height: 300px;">
            <div class="service-icon">
                <i class="fa fa-laptop"></i>
            </div>
            <h3>주문이 완료되었습니다.</h3>
            <p>flash 외 n개 총 flash 원 이 주문되었습니다.</p>
            <%= link_to '홈으로', root_path() %>
        </div>
    </div>
</div>

coffee/app/views/orders/index.html.erb
<section class="wrapper">
<section class="page_head">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
               <nav id="breadcrumbs">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li>Order</li>
                    </ul>
                </nav>

                <div class="page_title">
                    <h2>주문하기</h2>
                </div>
            </div>
        </div>
    </div>
</section>

    <section class="content elements">
    <div class="container">

    <div class="row sub_content">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dividerHeading">
                <h4><span>장바구니</span></h4>
            </div>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="promo_box">
                <div class="col-lg-9 col-sm-9">
                    <div class="promo_content">
                        <h3>내손으로 만드는 커피</h3>
                        <p>Lorem ipsum dolor sit amet, cons adipiscing elit. Aenean commodo ligula eget dolor. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12">
        <table class="table table-hover order-table">
            <thead class="text-center">
            <tr>
                <th class="col-lg-1 col-md-1 col-sm-1"></th>
                <th class="col-lg-6 col-md-6 col-sm-6">이름</th>
                <th class="col-lg-1 col-md-1 col-sm-1">가격</th>
                <th class="col-lg-1 col-md-1 col-sm-1">수량</th>
                <th class="col-lg-1 col-md-1 col-sm-1">총 가격</th>
                <th class="col-lg-2 col-md-2 col-sm-2"></th>
            </tr>
            </thead>
            <tbody>
            <% @products.each do |product| %>
                <tr>
                    <td><input type="checkbox" name="orderCheck" value="<%= product.id %>" checked=true ></td>
                    <td><%= product.name %></td>
                    <td id="pct_val_<%= product.id %>"><%= product.price %></td>
                    <td><input type="number" class="order-number" min="1"  id="pct_quant_<%= product.id %>" value="1"></td>
                    <td id="valQuant_<%= product.id %>"><%= product.price %></td>
                    <td>
                        <button class="btn btn-xs btn-success" type="button" id="">수정</button>
                        <button class="btn btn-xs btn-danger" type="button" style='margin-left: 4px;'>삭제</button>
                    </td>
                </tr>
            <% end %>
            <!-- 
            <tr>
                <td><input type="checkbox" name="orderCheck" value="1"></td>
                <td>정말정말 단 아메리카노</td>
                <td id="pct_val_1">5000</td>
                <td><input type="number" class="order-number" min="1"  id="pct_quant_1" value="1"></td>
                <td id="valQuant_1">5000</td>
                <td>
                    <div class="col-2 btn-group">
                        <button class="btn btn-xs btn-success" type="button" id="">수정</button>
                        <button class="btn btn-xs btn-danger" type="button" style='margin-left: 4px;'>삭제</button>
                    </div>
                </td>
            </tr>
            -->
            </tbody>
        </table>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="col-lg-10 col-sm-10">
                <div class="promo_content text-right" style="margin-top: 10px;">
                    <h3>총 가격 : <span id="totalVal">0<span></h3>
                </div>
            </div>
            <div class="col-lg-2 col-sm-2">
                <div class="pb_action">
                    <a class="btn btn-default btn-lg" id="orderBtn">
                        <i class="fa fa-check"></i>
                        주문하기
                    </a>
                </div>
            </div>
        </div>
    </div>

    </div> <!--./Container-->
    </section>
</section>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">정말 주문하시겠습니까?</h4>
      </div>
      
      <%= form_tag(orders_path, method: "post") do %>
        <%= hidden_field_tag(:checked_pct, "") %>
        <%= hidden_field_tag(:val_hidden, "") %>   
        <div class="modal-body">
            <p>총 가격은 <span id=valConfirm></span> 입니다.<p>
        </div>
        <div class="modal-footer">
        <%= submit_tag "주문하기", class: "btn btn-default" %>
            <button type="button" class="btn btn-default" data-dismiss="modal" id="ajax_order">주문하기</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">취소</button>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

<script>
$(document).ready(function (){
    
    // 전체가격 초기화
    orderIndex.totalValFn();

    // 수량을 클릭하면 총가격 수정하고 전체가격 수정
    $( "input[id*='pct_quant_']" ).on('input', function(event) {
        
        target = $(this).val();
        // 1보다 작으면 에러!
        if(target < 1) {
            
            alert("1보다 작을 수 없습니다!");
            target = 1;
        } else {
            
            // input에 소수점을 직접 타이핑 하는 경우 입력 가능
            // floor로 입력 유효성 검사
            target = Math.floor(target);
            
            // 클릭한 row의 id를 가져옴
            changedId = event.target.id.split("_")[2];

            // 그 row의 총 가격 = 가격 * 수량
            $("#valQuant_"+changedId).html(
                $("#pct_val_"+changedId).text() * $("#pct_quant_"+changedId).val() );        

        }
        
        // 전체가격 업데이트
        orderIndex.totalValFn();
    });

    // 체크박스를 클릭하면 전체 가격 초기화
    $( "input[type='checkbox']" ).on('click', function() {

        orderIndex.totalValFn();
    })
    
    // 주문하기 버튼을 클릭하면 모달 실행
    $("#orderBtn").click( function() {
        orderIndex.modalFn();
    });
})

var orderIndex = {

    // 전체가격 수정메서드입니다.
    totalValFn : function() {
        
        totalval = 0;

        // 총 가격을 모두 가져와서 totalVal에 저장합니다.
        $( "td[id*='valQuant_']" ).each(function(eachVal) {
            
            //총 가격의 줄에 체크박스를 가져와서
            $row_checkbox = $(this).parents("tr").children().eq(0).children();
            // 체크 되어 있다면 가격에 더한다.
            if($row_checkbox.prop("checked")) {
                totalval += +$(this).html();
            }
            
        })
        $("#totalVal").html(totalval);
    },

    modalFn : function() {

        $("#myModal").modal({
            show: true
        });

        // 체크된 pct의 id를 "n,n,n"형식으로 저장하기 위한 코드
        checked_pct = [];
        $("[name=orderCheck]").each(function(){
            
            if($(this).prop("checked")) {checked_pct.push($(this).val());}
        });
        
        // 체크한 pct목록을 hidden input에 추가
        $("#checked_pct").val(checked_pct);

        $("#val_hidden").val($("#totalVal").html());
        $("#valConfirm").html( $("#totalVal").html() );
    }
}
</script>

coffee/app/views/outlines/index.html.erb
<section class="wrapper">
    <!--end info service-->
    <!--Start recent work-->
    <section class="latest_work">
        <div class="container">
            <div class="paddingwork">
                <div class="container text-center">
                    <h1 class="hktitle" style="color:white">Likelion Coffee Project</h1>
                    <hr>
                    <h3 class="hktext" style="color:white">mini project</h3>
                    <div class="icons-container">
                        <!-- icon #1 -->
                        <div class="coffee-icon coffee-icon-1">
                            <div class="coffee-top"></div>
                            <div class="coffee-body"></div>
                        </div>
                        <!-- icon #2 -->
                        <div class="coffee-icon coffee-icon-2">
                            <div class="coffee-cup">
                                <div class="cup-lifter"></div>
                                <div class="coffee"></div>
                                <div class="cream">
                                    <div class="cream-part cream-part-1"></div>
                                    <div class="cream-part cream-part-2"></div>
                                    <div class="cream-part cream-part-3"></div>
                                    <div class="choco">
                                        <div class="choco-item choco-item-1"></div>
                                        <div class="choco-item choco-item-2"></div>
                                        <div class="choco-item choco-item-3"></div>
                                        <div class="choco-item choco-item-4"></div>
                                        <div class="choco-item choco-item-5"></div>
                                        <div class="choco-item choco-item-6"></div>
                                        <div class="choco-item choco-item-7"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- icon #3 -->
                        <div class="coffee-icon coffee-icon-3">
                            <div class="choco-bars"></div>
                            <div class="coffee-cup">
                                <div class="cream"></div>
                                <div class="coffee-cup-body">
                                    <div class="coffee">
                                        <div class="coffee-inner"></div>
                                    </div>
                                </div>
                                <div class="coffee-cup-lifter"></div>
                                <div class="coffee-cup-leg"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row sub_content">
                <div class="carousel-intro">
                    <div class="col-md-12">
                        <div class="dividerHeading">
                            <h4><span>Recent Work</span></h4>
                        </div>
                        <div class="carousel-navi">
                            <div id="work-prev" class="arrow-left jcarousel-prev"><i class="fa fa-angle-left"></i></div>
                            <div id="work-next" class="arrow-right jcarousel-next"><i class="fa fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<!--Start recent work-->
<!-- Parallax with Testimonial -->
<!--end wrapper-->
<script>
$('.flexslider.top_slider').flexslider({
    animation: "fade",
    controlNav: true,
    directionNav: true,
    prevText: "&larr;",
    nextText: "&rarr;"
});

$("body").attr("class", "home");
</script>

coffee/app/views/recipe/index.html.erb
<section class="wrapper">
  <!-- pagehead -->
  <section class="page_head">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12">
                  <nav id="breadcrumbs">
                      <ul>
                          <li><a href="index.html">Home</a></li>
                          <li>Make</li>
                      </ul>
                  </nav>

                  <div class="page_title">
                      <h2>레시피를 만드는 창입니다.</h2>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <!-- leftbar -->
  <section class="content left_sidebar">
    <div class="container">
      <div class="row">

        <!--Sidebar Widget-->
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="sidebar">

            <div class="widget widget_search">
              <div class="site-search-area">
                <form method="get" id="site-searchform" action="#">
                  <div>
                    <input class="input-text" name="s" id="s" placeholder="Enter Search keywords..." type="text" />
                    <input id="searchsubmit" value="Search" type="submit" />
                  </div>
                </form>
              </div><!-- end site search -->
            </div>

            <!-- 사이드바 주요부분 -->
            <div class="widget widget_categories">
              <div class="widget_title">
                <h4><span>Categories</span></h4>
              </div>
              <div class="panel-group accordion" id="accordion">
                <div class="panel panel-default">
                  <% @categories.each_with_index do |category, i| %>
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i %>">
                          <i class="switch fa fa-plus"></i>
                          <%= category.category  %>
                        </a>
                      </h4>
                    </div>
                    <div id="collapse<%= i %>" class="panel-collapse collapse">
                      <% @ingredients.where(category: category.category).each do |ingredient| %>
                          <div class="panel-body">
                              <div class="slidecontainer">
                                <div class="checkbox">
                                  <label><input type="checkbox" id="checkbox_<%=ingredient.id%>" name="ing_checkbox" value="<%=ingredient.id%>"><%= ingredient.name %></label>
                                  <input type="range" min="30" max="200" step="10" value="50" class="slider" id="ing_range_<%=ingredient.id%>">
                                  <p>
                                    가격 : <span id="ing_price_<%=ingredient.id%>"> <%= ingredient.price %> </span>| 
                                    용량: <span id="ing_value_<%=ingredient.id%>"></span> | 
                                    총 가격 : <span id="ing_total_value_<%= ingredient.id %>"></span> ￦
                                  </p>
                                </div>
                              </div>
                          </div>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- main content -->
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
          <div class="blog_large">
            <article class="post">
              <figure class="post_img">
                <!-- Post Image Slider -->
                <div class="post">
                  <div class="coffee">
                    <div class="handle"></div>
                    <div class="cup">
                      <div class="foam"><span>Milk Foam</span></div>
                      <div class="milk"><span>Steamed Milk</span></div>
                      <div class="water"><span>Water</span></div>
                      <div class="espresso"><span>Espresso</span></div>
                    </div>
                  </div>

                  <div class="btn-group" data-toggle="buttons-radio">
                    <button type="button" class="btn" data-nav="americano">Americano</button>
                    <button type="button" class="btn" data-nav="latte">Latte</button>
                    <button type="button" class="btn" data-nav="flat-white">Flat White</button>
                    <button type="button" class="btn" data-nav="cappuccino">Cappuccino</button>
                  </div>
                </div>
              </figure>

    
              <%= form_tag(recipe_index_path, method: "post") do %>
                <div class>
                  <div class="post_meta">
                      <h2>
                        <span>제품 이름 : <%=text_field_tag :pct_name, nil, required: true %> </span>
                        <span>가격 : <span id="whole_value">0</span>원 </span>
                      </h2>
                      <h4>제품 설명</h4>
                      <%= text_area_tag :pct_comment, nil, size: "24x6", placeholder: "당신의 제품은 어떤가요?", required: true  %>
                      <%= hidden_field_tag :pct_price, "" %>
                      <%= hidden_field_tag :checked, "1" %>
                    <div class="metaInfo">
                    </div>
                  </div>
                  <div style="display: flex;justify-content: flex-end;">
                    <div class="col-lg-2 col-md-2 col-xs-12">
                        <!-- Indicates caution should be taken with this action -->
                          <%= submit_tag "저장", class: 'btn btn-warning btn-block', id: "submitBtn"  %>
                    </div>
                  </div>
                </div>
              <%end%>
            </article>
          </div>
        </div>

      </div>
    </div>
  </section>
</section>

<!--end wrapper-->
<script>  
$(document).on('ready', function(){

    // 커피 그림부분
    // 이 부분은 건들지 않았습니다!!
    $('.btn-group button').on('click', function(e){
      e.preventDefault();
      $('.coffee').attr('data-type', $(this).attr('data-nav'));
    }).eq(0).trigger('click');

    ingredient.init(); // 슬라이더 초기세팅

    ingredient.checkbox_init(); // 체크박스를 클릭하면 값이 변경되는 이벤트 설정

    $("#submitBtn").on('click', function () {
      ingredient.check_hash();
    })
  });

  var ingredient = {
  
    // slider 초기값 세팅 & oninput 이벤트 추가
    init : function () {

      // 기존에 1개씩만 가져오던 코드를 고쳐서 한번에 담아버렸습니다.
      var sliders = $("[id*=ing_range_]");
      var outputs = $("[id*=ing_value_]");

      outputs.each(function (i) {           // 초기값 세팅
        
        $(this).html(50);
        var price = $(this).prev().html();
        $(this).next().html(price * 50);
      });

      // 슬라이더를 이동하면 밑에 값이 바뀌게
      sliders.on('input', function() {

        // 클릭한 슬라이더 id parsing
        var click_slider_id = $(this).attr("id").split("_")[2];
        
        // value : 부분에 변경된 값 넣기
        $("#ing_value_"+click_slider_id).html( $(this).val() );
        
        // 총가격 변경
        var price = +$("#ing_price_"+click_slider_id).html();
        var quantity = +$("#ing_value_"+click_slider_id).html();
        var totalV = price * quantity;

        $("#ing_total_value_"+click_slider_id).html(totalV);

        ingredient.whole_update();
      });
    },

    checkbox_init : function () {
      $("[name=ing_checkbox]").on('click', function() {
        ingredient.whole_update();
      });
    },

    //전체가격 업데이트
    whole_update : function() {

      var whole_value = 0;
      $("[id*=ing_total_value_]").each(function () {

        var id = $(this).attr('id').split("_")[3];
        var checkbox = $("#checkbox_" + id);
        
        if (checkbox.prop("checked")) {
          whole_value += +$(this).html();
        }
      });
      $("#whole_value").html(whole_value);
      $("#pct_price").val(whole_value);
    },

    // 체크박스 hash데이터
    // {체크박스 id : 수량}
    check_hash : function () {
      var checkedObj = {};

      $("[id*=ing_value_]").each(function () {

        var id = $(this).attr('id').split("_")[2];
        var checkbox = $("#checkbox_" + id);

        if (checkbox.prop("checked")) {
          checkedObj[id] = $(this).html();
        }
      });

      $("#checked").val(JSON.stringify(checkedObj));
    }
}
</script>